import '@/app/globals.css'

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { cn } from '@/lib/utils'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Nuoi Tao',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'font-sans antialiased min-h-dvh flex flex-col',
          geistSans.variable,
          geistMono.variable,
        )}
      >
        {children}

        <footer className='w-full border-t py-6 mt-auto bg-background text-muted-foreground text-center text-sm'>
          © {new Date().getFullYear()} Nuôi Tao. Được xây dựng với {'<'}4 tại
          Việt Nam.
        </footer>
      </body>
    </html>
  )
}
